#!/usr/bin/env ruby

require 'rubygems'
require 'eventmachine'
require 'json'
require 'logger'
require "yaml"

puts "Booting SocketServer..."

require File.dirname(__FILE__) + '/../config/environment'
require File.dirname(__FILE__) + '/../socket/ruby/server'


config_file = 'development'
config_file = ARGV[0][10..-1] if ARGV[0]

config_file = "config/socket/#{config_file}.yml"
puts "Loading config file:#{config_file}"
config = YAML.load(open(config_file, "rb"){|fh| fh.read})

EventMachine::run {
  host, port = config["network"]["host"], config["network"]["port"]
  puts "Now accepting connections on address #{host}, port #{port}..."
  EventMachine::start_server host, port, SocketServer
}